# Generated by Django 4.1.5 on 2023-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdb',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='countdb',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
